dist: trusty
sudo: required
language: java
jdk: openjdk7
cache:
  directories:
    - $HOME/.m2
before_install:
  - ./travis/install_protobuf.sh
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
group: stable
os: linux
